name: googlemap2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  google_map_polyline_new: ^0.3.0+2
  flutter_polyline_points: ^1.0.0
  location: ^5.0.3
  geolocator: ^10.1.0
  flutter_google_places: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
